favicon: null
name: Pugs Forever
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.875
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#D4E5F7'
    - '#6E90B3'
    - '#050D02'
    - '#B7A98F'
    - '#445533'
  rhythmicContrast: 0.25
typography_spectrum: 0.495221
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.61291
analytics:
  twitter: null
  google: null
  facebook: null
